config/routes.rb
ActionController::Routing::Routes.draw do |map|

  

  
  map.admin "admin", :controller => "admin/painel", :action => "index"
  map.admin_login "admin/login", :controller => "admin/acesso", :action => "login"
  map.admin_logout "admin/logout", :controller => "admin/acesso", :action => "logout"
  map.namespace :admin do |admin|
    admin.resources :administradores
    admin.resources :produtos, :collection => { :new_combo => :get,
                                                :create_combo => :post,
                                                :print => :get },
                               :member => { :edit_combo => :get,
                                            :update_combo => :put,
                                            :relacionar => :get,
                                            :remover_relacionar => :get,
                                            :print => :get }
    admin.resources :pedidos, :collection => { :print => :get,
                                               :lista_ceps => :get,
                                               :controle_postagem => :get },
                              :member => { :print => :get,
                                           :alterar_status => :get,
                                           :envelopado => :post,
                                           :nf_marcar => :post,
                                           :gravar_cod_postagem => :post }
    
    admin.resources :descontos
    admin.resources :configuracoes, :collection => { :editar_arquivo => :post,
                                                     :salvar_arquivo => :post,
                                                     :salvar => :post,
                                                     :frete_por_estado => :get,
                                                     :frete_por_estado_salvar => :post,
                                                     :frete_por_estado_incluir_row => :post }
    admin.resources :relatorios
    admin.resources :automacoes, :collection => { :entrar_arquivo => :get,
                                                  :processar_dados => :post,
                                                  :relatorios => :get,
                                                  :desmarcar_todos => :get,
                                                  :nota_fiscal_avulsa => :get },
                                 :member => { :confirmar_pagamento => :post }
  end

  map.root :controller => 'home'

  map.connect '/videos/:action', :controller => 'videos'
  map.connect '/pelucia', :controller => 'videos', :action => 'pelucia'
  map.connect '/caixinha-de-musica', :controller => 'videos', :action => 'cd_caixinha_musica'
  map.fale_conosco '/fale-conosco', :controller => 'fale_conosco'
  map.quem_somos '/quem-somos', :controller => 'fale_conosco', :action => 'quem_somos'
  map.iphone '/iphone', :controller => 'fale_conosco', :action => 'iphone'
  map.iphone '/patrocinadores', :controller => 'fale_conosco', :action => 'patrocinadores'

  map.pagseguro '/retorno_uolpagseguro', :controller => 'comprar', :action => 'confirmacao_uol'
  
  map.connect '/letras/galinha-pintadinha', :controller => 'letras', :action => 'galinha_pintadinha'
  map.connect '/letras/o-sapo', :controller => 'letras', :action => 'o_sapo'
  map.connect '/letras/a-barata', :controller => 'letras', :action => 'a_barata'
  map.connect '/letras/pintinho-amarelinho', :controller => 'letras', :action => 'pintinho_amarelinho'
  map.connect '/letras/marcha-soldado', :controller => 'letras', :action => 'marcha_soldado'
  map.connect '/letras/fli-flai', :controller => 'letras', :action => 'fli_flai'
  map.connect '/letras/escravos-de-jo', :controller => 'letras', :action => 'escravos_de_jo'
  map.connect '/letras/quem-esta-feliz', :controller => 'letras', :action => 'quem_esta_feliz'

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  # Quem fez o pedido
  belongs_to :pessoa
  
  # Produtos e Quantidades associados
  has_many :produtos_quantidades
  has_many :produtos, :through => :produtos_quantidades
  
  # Retornos do UOLPagSeguro
  has_many :retornos_pgmtos
  
  # Tabela descontos (associados aos pedidos; aqui guarda-se só o valor)
  has_one :cupom_de_desconto, :class_name => "Desconto", :autosave => true
  
  # Para mudanca de status...
  attr_accessor :mudar_para
  
  #===========================================================================#
  #                             VALIDATIONS                                   #
  #===========================================================================#
  validate :must_have_one_produto
  validate :must_not_have_produtos_iguais
  #validate :validate_pessoa
  validates_associated :pessoa
  validates_presence_of :entrega_endereco
  validates_presence_of :entrega_numero
  validates_presence_of :entrega_cep
  validates_presence_of :entrega_cidade 
  validates_presence_of :entrega_estado
  validates_length_of :entrega_endereco, :maximum => 100, :allow_nil => true
  validates_length_of :entrega_numero, :maximum => 10, :allow_nil => true
  validates_length_of :entrega_cidade, :maximum => 50, :allow_nil => true
  validates_length_of :entrega_estado, :maximum => 2, :allow_nil => true
  validates_length_of :entrega_cep, :is => 8
  validates_numericality_of :entrega_cep, :only_integer => true
  
  def must_have_one_produto
    if (produtos_quantidades.size <= 0)
      errors.add_to_base("Carrinho precisa de ao menos um produto")
    end
  end
  
  def must_not_have_produtos_iguais
    produtos_ids = []
    produtos_quantidades.each { |c| produtos_ids << c.produto_id }
    if produtos_ids.size != produtos_ids.uniq.size
      errors.add_to_base("Carrinho tem rows com produtos iguais")
    end
  end
  
  # Another option to validate pessoa...
  def validate_pessoa
    if pessoa && !pessoa.valid?
      pessoa.errors.each { |attr, msg| errors.add(attr, msg) }
    end
  end

  #===============================================================================#
  #                               NAMED SCOPES                                    #
  #===============================================================================#
  named_scope :feitos_antes_de, lambda { |data|
    if data.blank?
      {}
    else
      { :conditions => ["pedidos.created_at <= ?", data] }
    end
  }
  named_scope :feitos_dias_atras, lambda { |data|
    if data.blank?
      {}
    else
      { :conditions => ["DATE(pedidos.created_at) = DATE(?)", data] }
    end
  }
  named_scope :posteriores_a, lambda { |data|
    if data.blank?
      {}
    else
      { :conditions => ["pedidos.data_envio >= ?", data] }
    end
  }
  named_scope :anteriores_a, lambda { |data|
    if data.blank?
      {}
    else
      { :conditions => ["pedidos.data_envio <= ?", data] }
    end
  }
  named_scope :nf_inicial, lambda { |nf_numero|
    if data.blank?
      {}
    else
      { :conditions => ["pedidos.nota_fiscal >= ?", nf_numero] }
    end
  }
  named_scope :nf_final, lambda { |nf_numero|
    if data.blank?
      {}
    else
      { :conditions => ["pedidos.nota_fiscal <= ?", nf_numero] }
    end
  }
  named_scope :com_status, lambda { |varios_status|
    if varios_status.blank?
      {}
    else
      if varios_status.kind_of?(String)
        { :conditions => ["pedidos.status IN (?)", varios_status] }
      elsif varios_status.kind_of?(Array)
        tmp = []
        varios_status.each { |k| tmp << "pedidos.status = '#{k}'" }
        { :conditions => [ tmp.join(' OR ') ] }
      end      
    end
  }
  named_scope :forma_pgmto, lambda { |diversas|
    if diversas.blank?
      {}
    else
      if diversas.kind_of?(String)
        { :conditions => ["pedidos.forma_pgmto IN (?)", diversas] }
      elsif diversas.kind_of?(Array)
        tmp = []
        diversas.each { |k| tmp << "pedidos.forma_pgmto = '#{k}'" }
        { :conditions => [ tmp.join(' OR ') ] }
      end      
    end
  }


  #==================================================================#
  #                           METHODS                                #
  #==================================================================#
  # Inclui os produtos e suas respectivas qtds no pedido
  # TODO: onde isto é usado?? REMOVE-ME!!!
  def inclui_produtos_qtd(options = {})
    if options.include?('id') and options.include?('qtd')
      pq = ProdutosQuantidade.new(:pedido_id => self.id,
                                  :produto_id => options[:id],
                                  :qtd => options[:qtd],
                                  :presente => options.include?('presente'))
      pq.save!
    end
  end
  
  # Retorna o nome da pessoa para quem vai o(s) presente(s)
  def para
    if not self.entrega_nome_pacote.blank?
      self.entrega_nome_pacote
    else
      if self.pessoa
        self.pessoa.nome
      else
        "Pedido sem pessoa relacionada"
      end
    end
  end
  
  # Calcula o valor total do pedido
  def total
    t  = self.total_sem_frete_sem_desconto
    t += self.frete.to_f if self.frete
    t -= self.desconto.to_f if self.desconto
    return t.to_f
  end

  def total_sem_frete_sem_desconto
    t = 0
    if self.produtos_quantidades
      for p in self.produtos_quantidades
        t += p.qtd.to_i * p.preco_unitario.to_f
      end
    end
    return t.to_f
  end
  
  # Retorna quantos itens tem o pedido
  # (i.e. a QUANTIDADE total de itens pedidos)
  def n_itens
    n = 0
    self.produtos_quantidades.each { |c| n += c.qtd }
    return n
  end
  
  # Retorna quantas linhas ha na nota-fiscal do produto
  def n_linhas_nota_fiscal
    n = 0
    self.produtos_quantidades.each do |pq|
      if pq.produto.class == ProdutoCombo
        n += pq.produto.produtos.size
      else
        n += 1
      end
    end
    return n    
  end
  
  # CEP no formato DDDDD-DDD
  def cep
    self.entrega_cep[0..4]+"-"+self.entrega_cep[5..8] if self.entrega_cep
  end
  
  # Tira o hifen, quando houver
  def entrega_cep=(valor)
    valor.gsub!(/[-]/,'') if valor.include?('-')
    write_attribute(:entrega_cep, valor)
  end
  
  # Transforma o Id em Letras(=Base50)
  # Vide: lib/salt.rb
  def base50
    Salt.converteParaBase50(self.id)
  end
  
  # Verifica se tais dados batem
  # pois só seu dono os possui.
  def check(pid, pbase, chkpid, md5)
    return ((self.id.to_i == pid.to_i) and 
            (self.base50 == pbase) and
            (self.pessoa_id.to_i == chkpid.to_i) and
            (self.pessoa.md5 == md5))
  end
  
  # Métodos para ACTIVE SCAFFOLD
  # Reescritos no Helper.
  #=============================
  # REMOVE-ME!!!
  #def to_label
  #  "PedidoId #{self.id}, feito por #{self.pessoa.primeiro_nome} em #{self.created_at.strftime('%d de %B')}"
  #end
  
  def endereco
  end
  
  def change_status
  end  
    
  #============================================================================#
  #                            ESTADOS dos PEDIDOS                             #
  #============================================================================#
  acts_as_state_machine :initial => :pedido, :column => 'status'

  # Estados disponíveis para os PEDIDOS
  state :pedido,                       :after => Proc.new {|model| model.inicia_pedido }
  state :aguardando_pagamento,         :after => Proc.new {|model| model.notifica_recebimento_pedido }
  state :processando_envio,            :after => Proc.new {|model| model.pedido_pago }
  state :processando_envio_envelopado, :after => Proc.new {|model| model.pedido_envelopado }
  state :processando_envio_notafiscal, :after => Proc.new {|model| model.pedido_notafiscal }
  state :produto_enviado,              :after => Proc.new {|model| model.envia_produto }
  state :produto_enviado_cod_postagem, :after => Proc.new {|model| model.insere_cod_postagem }
  state :pedido_cancelado,             :after => Proc.new {|model| model.notifica_cancelamento }
  state :recebido_pelo_cliente,        :after => Proc.new {|model| model.depois_de_recebido }
  state :encerrado,                    :after => Proc.new {|model| model.notifica_encerramento }

  # Inicia o pedido
  event :iniciar do
    transitions :from => :pedido,                       :to => :aguardando_pagamento
  end
  
  # Confirma o pagamento
  event :pagamento_confirmado do
    transitions :from => :aguardando_pagamento,         :to => :processando_envio
  end

  # Envelopa o pedido
  event :envelopar do
    transitions :from => :processando_envio,            :to => :processando_envio_envelopado
  end

  # Imprime a nota fiscal do pedido
  event :imprimir_nota_fiscal do
    transitions :from => :processando_envio_envelopado, :to => :processando_envio_notafiscal
  end
  
  # Manda o produto ao correio
  event :enviar_correio do
    transitions :from => :processando_envio,            :to => :produto_enviado
    transitions :from => :processando_envio_envelopado, :to => :produto_enviado
    transitions :from => :processando_envio_notafiscal, :to => :produto_enviado
  end
  
  # Insere no pedido o codigo de postagem 
  event :incluir_cod_postagem do
    transitions :from => :produto_enviado,              :to => :produto_enviado_cod_postagem
  end
  
  # CLIENTE notifica que recebeu produto
  event :cliente_recebeu do
    transitions :from => :produto_enviado_cod_postagem, :to => :recebido_pelo_cliente
  end
  
  # Cancelar pedido
  event :cancelar do
    transitions :from => :aguardando_pagamento,         :to => :pedido_cancelado
    transitions :from => :processando_envio,            :to => :pedido_cancelado
  end
  
  # Encerrar pedido
  event :encerrar do
    #transitions :from => :aguardando_pagamento,        :to => :encerrado
    transitions :from => :processando_envio,            :to => :encerrado
    transitions :from => :processando_envio_envelopado, :to => :encerrado
    transitions :from => :processando_envio_notafiscal, :to => :encerrado

app/helpers/admin/folhamatic/produtos_helper.rb
module Admin::Folhamatic::ProdutosHelper

  # REGISTRO: E020- CADASTRO DE PRODUTOS/SERVIÇOS
  # Este registro importará os dados para o Cadastro de Produtos/Serviços do sistema. Atenção para as observações abaixo:
  # - Se o cadastro do produto/serviço já existir no sistema, ao importar, os dados do mesmo serão sobrepostos.
  # - Se foram feitas alterações do tipo ortográficas (corretivas) no cadastro, importe o registro E020 deixando os campos 05 e 07 vazios, preenchendo no campo 06 a data do Período Inicial de Utilização do produto/serviço.
  # - Se o cadastro do produto/serviço sofreu alterações cadastrais (ex. alteração na descrição), gere um registro E020 com os dados já atualizados e
  # com os campos 05 e 07 vazios, preenchendo no campo 06 a data do Período Inicial de Utilização do produto/serviço, e gere também um registro
  # E020 com os dados anteriores informando nos campos 06 e 07 a data inicial e final dos dados anteriores. Quando a alteração cadastral for na
  # descrição do produto/serviço, informe também no campo 05 a data em que o cadastro sofreu a alteração, caso contrário, deixe este campo vazio.
  def e020_cadastro_de_produtos_servicos
    return "implementar, se preciso"
  end

end

app/views/admin/produtos/_form.html.erb
<div class="grid_6 alpha">
<fieldset>
  <ol>
    <li>
      <label class="checkbox">Produto disponível</label>
      <%= f.check_box :disponivel %>
    </li>
    <li>
      <label>Nome</label>
      <%= f.text_field :nome, :size => 55 %>
    </li>
    <li>
      <label>Descrição</label>
      <%= f.text_area :descricao, :rows => 3, :cols => 48 %>
      <p class="dica">Descrição sucinta (porém informativa) sobre o produto.</p>
    </li>
    <li>
      <label>Descrição fiscal</label>
      <%= f.text_field :descricao_simples, :size => 55 %>
      <p class="dica">Descrição impressa na nota fiscal.</p>
    </li>
    <li class="small">
      <label>Em estoque</label>
      <%= f.text_field :qtd_estoque, :size => 6 %>
    </li>
    <li class="small">
      <label>Peso</label>
      <%= f.text_field :peso, :size => 6 %>
      <p class="dica">Em gramas.</p>
    </li>
    <li>
      <label>Tamanho</label>
      <%= f.text_field :tamanho, :size => 26 %>
      <p class="dica">Alt. (cm) x Larg. (cm) x Prof. (cm)</p>
    </li>
    <li>
      <label>Imagens</label>
      <b>/images/produtos/</b><%= f.text_field :imagem_pequena %>
      <p class="dica">Indique acima a imagem principal (ex.: dvd1.png)<br />
        Suba a(s) imagem(ns) para a pasta indicada acima.<br />
        Para thumbnails, acrescente <b>_thumb</b> (ex.: dvd1_thumb.png)
      </p>
    </li>
  </ol>
</fieldset>
</div>
<!-- COLUNA DA DIREITA -->
<div class="grid_6 omega">
  <fieldset>
    <ol>
      <li class="big green">
        <label>Preço</label>
        R$ <%= f.text_field :preco, :size => 4 %>
        <p class="dica">Use ponto para separar os centavos.</p>
      </li>
      <li>
        <label>Preço fiscal</label>
        R$ <%= f.text_field :preco_fiscal, :size => 4 %>
        <p class="dica">Use ponto para separar os centavos.</p>
      </li>
      <li>
        <label>Acréscimo para presente</label>
        R$ <%= f.text_field :plus_presente, :size => 4 %>
        <p class="dica">Use ponto para separar os centavos.</p>
      </li>
    </ol>
  </fieldset>
</div>

app/views/admin/produtos/_form_produto_combo.html.erb
<!-- COMBO -->
<div class="grid_6 alpha">
<fieldset>
  <ol>
    <li>
      <label class="checkbox">Produto disponível</label>
      <%= f.check_box :disponivel %>
    </li>
    <li>
      <label>Nome</label>
      <%= f.text_field :nome, :size => 55 %>
    </li>
    <li>
      <label>Descrição</label>
      <%= f.text_area :descricao, :rows => 3, :cols => 48 %>
      <p class="dica">Descrição sucinta (porém informativa) sobre o produto.</p>
    </li>
    <li>
      <label>Descrição simples</label>
      <%= f.text_field :descricao_simples, :size => 55 %>
      <p class="dica">Descrição impressa na nota fiscal.</p>
    </li>
    <!--li class="small">
      <label>Em estoque</label>
      <%= f.text_field :qtd_estoque, :size => 6 %>
    </li-->
    <li class="small">
      <label>Peso</label>
      <%= f.text_field :peso, :size => 6 %>
      <p class="dica">Em gramas.</p>
    </li>
    <li>
      <label>Tamanho</label>
      <%= f.text_field :tamanho, :size => 26 %>
      <p class="dica">Alt. (cm) x Larg. (cm) x Prof. (cm)</p>
    </li>
    <li>
      <label>Imagens</label>
      <b>/images/produtos/</b><%= f.text_field :imagem_pequena %>
      <p class="dica">Apenas a raiz do nome do arquivo (ex.: <b>dvd1</b> de <i>dvd1.png</i>)</p>
    </li>
  </ol>
</fieldset>
</div>
<!-- COLUNA DA DIREITA -->
<div class="grid_6 omega">
  <fieldset>
    <ol>
      <li>
        <label>Produtos do pacote</label>
        <%= select_tag "produto_combo[produto_ids][]",
                       options_from_collection_for_select(@produtos, 'id', 'nome', @produto.produto_ids), 
                       :multiple => true,
                       :style => "height:100px;width:200px" %>
      </li>
      <!-- li id="li_total">
        <label>Total</label>
        R$ <span id="total"></span>
      </li -->
      <li class="big green">
        <label>Desconto</label>
        R$ <%= f.text_field :desconto, :size => 4 %>
        <p class="dica">Use ponto para separar os centavos.</p>
      </li>
      <li>
        <label>Acréscimo para presente</label>
        R$ <%= f.text_field :plus_presente, :size => 4 %>
        <p class="dica">Use ponto para separar os centavos.</p>
      </li>
    </ol>
  </fieldset>
</div>

app/views/admin/produtos/_form_produto_simples.html.erb
<div class="grid_6 alpha">
<fieldset>
  <ol>
    <li>
      <label class="checkbox">Produto disponível</label>
      <%= f.check_box :disponivel %>
    </li>
    <li>
      <label>Nome</label>
      <%= f.text_field :nome, :size => 55 %>
    </li>
    <li>
      <label>Descrição</label>
      <%= f.text_area :descricao, :rows => 3, :cols => 48 %>
      <p class="dica">Descrição sucinta (porém informativa) sobre o produto.</p>
    </li>
    <li>
      <label>Descrição simples</label>
      <%= f.text_field :descricao_simples, :size => 55 %>
      <p class="dica">Descrição impressa na nota fiscal.</p>
    </li>
    <li class="small">
      <label>Em estoque</label>
      <%= f.text_field :qtd_estoque, :size => 6 %>
    </li>
    <li class="small">
      <label>Peso</label>
      <%= f.text_field :peso, :size => 6 %>
      <p class="dica">Em gramas.</p>
    </li>
    <li>
      <label>Tamanho</label>
      <%= f.text_field :tamanho, :size => 26 %>
      <p class="dica">Alt. (cm) x Larg. (cm) x Prof. (cm)</p>
    </li>
    <li>
      <label>Imagens</label>
      <b>/images/produtos/</b><%= f.text_field :imagem_pequena %>
      <p class="dica">Apenas a raiz do nome do arquivo (ex.: <b>dvd1</b> de <i>dvd1.png</i>)</p>
    </li>
  </ol>
</fieldset>
</div>
<!-- COLUNA DA DIREITA -->
<div class="grid_6 omega">
  <fieldset>
    <ol>
      <li class="big green">
        <label>Preço</label>
        R$ <%= f.text_field :preco, :size => 4 %>
        <p class="dica">Use ponto para separar os centavos.</p>
      </li>
      <li>
        <label>Preço fiscal</label>
        R$ <%= f.text_field :preco_fiscal, :size => 4 %>
        <p class="dica">Use ponto para separar os centavos.</p>
      </li>
      <li>
        <label>Acréscimo para presente</label>
        R$ <%= f.text_field :plus_presente, :size => 4 %>
        <p class="dica">Use ponto para separar os centavos.</p>
      </li>
    </ol>
  </fieldset>
</div>

app/views/admin/produtos/edit.html.erb
<h1>Editar produto</h1>

<% form_for(@produto, :url => admin_produto_path(@produto), :html => { :multipart => true }) do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form_produto_simples", :locals => { :f => f } %>
  <p class="form_button"><%= f.submit "Salvar" %> ou <%= link_to "Voltar", admin_produtos_path %></p>
<% end %>

app/views/admin/produtos/edit_combo.html.erb
<h1>Editar Combo</h1>

<% form_for(@produto, :url => { :action => "update_combo", :id => @produto }, :html => { :multipart => true }) do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form_produto_combo", :locals => { :f => f } %>
  <p class="form_button"><%= f.submit "Salvar" %> ou <%= link_to "Voltar", admin_produtos_path %></p>
<% end %>

app/views/admin/produtos/index.html.erb
<h1>Produtos</h1>
<p style="padding-bottom:30px">
  <%= link_to(content_tag(:span, image_tag("icones/add.png") + " Novo Produto Simples"), new_admin_produto_path, :class => "botao") %>
  <%= link_to(content_tag(:span, image_tag("icones/add.png") + " Novo Combo"), { :action => "new_combo" }, :class => "botao") %>
</p>
<table id="lista_de_produtos" class="crud">
  <thead>
    <tr>
      <th><img src="/images/icones/disponivel.gif" alt="disponivel"></th>
      <th>Estoque</th>
      <th>Nome/Descrição simples</th>
      <th>Preço</th>
      <th colspan="1">
        Ações
      </th>
    </tr>
  </thead>
<% for produto in @produtos -%>
  <tr class="<%= produto.class.to_s.downcase %>">
    <td class="estreita">
      <% if produto.disponivel -%>
        <img src="/images/icones/disponivel.gif" alt="disponivel">
      <% else -%>
        <img src="/images/icones/disponivel_not.gif" alt="disponivel">
      <% end -%></td>
    <td class="estreita grandao">
      <span class="<%= "vermelho" if (produto.qtd_estoque <= 0) %>"><%= produto.qtd_estoque %></span>
    </td>
    <td>
      <%= produto.nome %><br />
      <span class="pequeno cinza"><%= produto.descricao_simples %></span>
    </td>
    <td class="grandao green"><%= number2currency(produto.preco) %></td>
    <td class="acoes">
      <% if (produto.class == ProdutoSimples) -%>
        <%= link_to image_tag("icones/database_edit.png") + " Editar", edit_admin_produto_path(produto) %><br />
      <% elsif (produto.class == ProdutoCombo) -%>
        <%= link_to image_tag("icones/database_edit.png") + " Editar", :action => "edit_combo", :id => produto %><br />
      <% end -%>
      <%= link_to image_tag("icones/link_add.png") + " Relacionar", :action => "relacionar", :id => produto %><br />
      <%= link_to image_tag("icones/cancel.png") + " Remover", admin_produto_path(produto), :confirm => "Tem certeza?", :method => :delete %>
    </td>
  </tr>
<% end -%>
</table>

<%= will_paginate(@produtos) %>

<style type="text/css" media="screen">
.remover { width: 80px; }
.produtocombo { background-color:#ffd;}
</style>

app/views/admin/produtos/new.html.erb
<h1>Novo produto simples</h1>

<% form_for(@produto, :url => admin_produtos_path, :html => { :multipart => true }) do |f| %>
  <%= error_messages_for :produto %>
  <%= render :partial => "form_produto_simples", :locals => { :f => f } %>
  <p class="form_button"><%= f.submit "Salvar" %> ou <%= link_to "Voltar", admin_produtos_path %></p>
<% end %>

app/views/admin/produtos/new_combo.html.erb
<h1>Novo Combo</h1>

<% form_for(@produto, :url => { :action => "create_combo" }, :html => { :multipart => true }) do |f| %>
  <%= error_messages_for :produto %>
  <%= render :partial => "form_produto_combo", :locals => { :f => f } %>
  <p class="form_button"><%= f.submit "Salvar" %> ou <%= link_to "Voltar", admin_produtos_path %></p>
<% end %>

app/views/admin/produtos/relacionar.html.erb
<h1>Relacionar Produtos</h1>

<% form_for(@produto, :url => { :action => "gravar_relacionar", :id => @produto }, :html => { :multipart => true }) do |f| %>
  <%= f.error_messages %>
    
  <div class="grid_4 alpha">
    <div id="relacionados" style="background-color:#eee;padding:5px;border:1px solid gray">
      <h3>Produtos relacionados</h3>
      <% if @produto.produtos_relacionados.empty? -%>
        <p>Ainda não há produtos relacionados ao <b><%= @produto.nome %></b>.</p>
        <p>Crie já um relacionamento, arrastando os produtos à direita.</p>
      <% else -%>
      <ul>
        <% @produto.produtos_relacionados.each do |s| -%>
        <li id="relacionado_<%= s.id %>" class="sans-bullet">
          <%= link_to image_tag("icones/link_break.png"), 
                      { 
                        :action => "remover_relacionar",
                        :id => @produto.id,
                        :relacionado => s.id 
                      },
                      :confirm => "Quer mesmo excluir essa relação?" -%> <b><%= s.nome -%></b>
        </li>
        <% end -%>
      </ul>
      <p class="legenda">Use o ícone <%= image_tag("icones/link_break.png") %> para remover o relacionamento.</p>
      <% end -%>
    </div>
  </div>
  
  <div class="grid_3">
    <div id="criar_relacao" style="background-color:#FFE69F;padding:5px;border:1px solid yellow">
      <h3>Relacionar!</h3>
      <p>Arraste para cá os produtos que deseja relacionar a...</p>
      <%= drop_receiving_element("criar_relacao", 
                                 :url => { :action => "add" },
                                 :onDrop => "function(draggable_element, droppable_element, event) { relacionarProduto(#{@produto.id}, draggable_element.id) }",
                                 #:update => "relacionados",
                                 :confirm => "Quer mesmo relacionar esse produto a '#{@produto.nome}'?") %>
      <div id="em_questao">
        <%= infos_produto_box(@produto, :link_to_carrinho => false) %>
      </div>
      <p class="legenda">Os produtos relacionados aqui aparecerão na <b>Sugestão da Galinha</b>.</p>
    </div>
  </div>
  
  <div class="grid_5 omega">
    <h3>Demais produtos</h3>
    <ul>
    <% @demais_produtos.each do |p| -%>
      <li class="sans-bullet demais_produtos" id="produto_<%= p.id %>" value="<%= p.id %>">
        <%= infos_produto_box(p, :link_to_carrinho => false) %>
        <%= draggable_element("produto_#{p.id}") %>
      </li>
    <% end -%>
    </ul>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
function relacionarProduto(produto_id, elem_id) {
  if ($(elem_id)) {
    location.href='/admin/produtos/'+produto_id+'/relacionar?novo=1&produto_id='+$(elem_id).value;
    //alert($(elem_id).value);
  }
}
</script>